OBJS = main.cpp

CC = g++

INCLUDE_PATHS = -I/usr/local/include
LIBRARY_PATHS = -L/user/local/lib

COMPILER_FLAGS = -w

LINKER_FLAGS = -framework OpenGL -lglfw3 -lglew

OBJ_NAME = main

all : $(OBJS); $(CC) $(OBJS) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)

